(function(g){var window=this;var yza=function(a,b,c,d){c=(0,g.A)(c,d||a.A);b=g.PG(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},zza=function(a){a.o||(a.o=new g.YD,g.K(a,a.o));
return a.o},h2=function(a){a.V("cardstatechange",a.fe()&&a.ue()?1:0)},Dza=function(a){var b=g.Oh(a,"fontSize");
var c=(c=b.match(Aza))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.$d){if(String(c)in Bza)return g.fi(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Cza)return a=a.parentNode,c=g.Oh(a,"fontSize"),g.fi(a,b==c?"1em":b,"left","pixelLeft")}c=g.ee("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.me(c);return b},i2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},Eza=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.cl&&a.dataset){if(g.nc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Bc("pollChoiceIndex"))},l2=function(a){a=g.Ka(a);
delete j2[a];g.ac(j2)&&k2&&k2.stop()},Gza=function(){k2||(k2=new g.U(function(){Fza()},20));
var a=k2;a.isActive()||a.start()},Fza=function(){var a=(0,g.H)();
g.Jb(j2,function(b){Hza(b,a)});
g.ac(j2)||Gza()},Iza=function(a,b){g.Cf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},m2=function(a,b,c,d){g.zu.call(this);
if(!g.Fa(a)||!g.Fa(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.C=null},Hza=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.C);a.C=b;Jza(a,a.progress);1==a.progress?(a.o=0,l2(a),a.Ld(),a.Dn()):a.ub()&&a.Lw()},Jza=function(a,b){g.Ha(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},n2=function(a,b,c,d,e){m2.call(this,b,c,d,e);
this.element=a},o2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
n2.apply(this,arguments)},Kza=function(a){return Math.pow(a,3)},Lza=function(a){return 3*a*a-2*a*a*a},p2=function(a,b){(0,g.C)(b,function(b){g.DH("visualElementShown",{csn:a,
ve:g.MH(b),eventType:4},g.IH,void 0,void 0)})},q2=function(a,b){(0,g.C)(b,function(b){g.DH("visualElementHidden",{csn:a,
ve:g.MH(b),eventType:8},g.IH,void 0,void 0)})},r2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Nd=b.session_data||{};this.B=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={PM:a.impression,click:a.click,close:a.close,dW:a.teaser_impression,Tx:a.teaser_click};b=b.tracking_params||{};this.F=g.LH(b.card);this.H=g.LH(b.teaser);this.D=g.LH(b.icon)},s2=function(a,b){g.dg.call(this);
this.Gm=a;this.Fu=b;this[g.Hf]=!1},w2=function(a,b,c,d){s2.call(this,a,b);
a=this.Fu;b=this.sa();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.Za(),g.u(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Mza(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Fu;a=this.sa();if(d instanceof t2)a.setAttribute("fill",d.J),a.setAttribute("fill-opacity",d.K);else if(d instanceof u2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=v2(c,"linearGradient",{x1:d.D,
y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.Ba(d.B)&&(f+=";stop-opacity:"+d.B);f=v2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.Ba(d.C)&&(f+=";stop-opacity:"+d.C);d=v2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=Nza(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},Oza=function(){},Pza=function(a,b){s2.call(this,a,b)},x2=function(){this.wb=[];
this.Ra=[];this.Le=[]},y2=function(a,b,c,d){var e=a.ie[0]-b*Math.cos(g.Kd(d))+b*Math.cos(g.Kd(d+90)),f=a.ie[1]-c*Math.sin(g.Kd(d))+c*Math.sin(g.Kd(d+90));
a.wb.push(3);a.Ra.push(1);a.Le.push(b,c,d,90,e,f);a.Sn=!1;a.ie=[e,f]},Rza=function(a,b){for(var c=a.Le,d=0,e=0,f=a.wb.length;e<f;e++){var k=a.wb[e],l=Qza[k]*a.Ra[e];
b(k,c.slice(d,d+l));d+=l}},Sza=function(a,b,c,d){w2.call(this,a,b,c,d)},z2=function(a,b){this.A=a;
this.o=b},A2=function(a,b,c,d,e){g.Xv.call(this,e);
this.width=a;this.height=b;this.C=c||null;this.R=d||null},Mza=function(a){var b=a.Xj();
return b?b.width/(a.C?new g.Nd(a.C,a.R):a.Xj()).width:0},Tza=function(a,b){s2.call(this,a,b)},u2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.B=g.za(k)?k:null;this.C=g.za(l)?l:null},t2=function(a,b){this.J=a;
this.K=null==b?1:b},B2=function(a,b){s2.call(this,a,b)},Uza=function(a,b,c,d){w2.call(this,a,b,c,d)},C2=function(a,b){s2.call(this,a,b)},D2=function(a,b,c,d,e){A2.call(this,a,b,c,d,e);
this.A={};this.N=g.be&&!g.Jc(526);this.K=new g.Ln(this)},v2=function(a,b,c){a=a.J.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&E2(a,c);return a},E2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},F2=function(a,b,c,d){b=v2(a,"path",{d:Vza(b)});
c=new Uza(b,a,c,d);a.B.sa().appendChild(c.sa())},Vza=function(a){var b=[];
Rza(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},Nza=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+Wza++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},Xza=function(){G2||(G2=new g.Og(400),G2.start());
return G2},H2=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.I)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.I)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.LH(a.trackingParams);var k=(0,g.I)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.RA=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.I)(x.loggingUrls||[],c);l.xo=g.Tb(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.I)(k.impressionUrls||[],c);l.bM=(0,g.I)(k.hovercardShowUrls||[],c);l.Nd={itct:k.trackingParams};l.visualElement=g.LH(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.Qp=!1,l.Ir=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.Qp=!1,l.Ir=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.Tb(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Qp=!1;l.Ir="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var y=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var G=d(m.subscriberCountText)}else E=d(m.subscriberCountText),G=d(m.subscriberCountWithSubscribeText);
var N=null;if(k.signinEndpoint&&(N=g.Tb(k,"signinEndpoint","webNavigationEndpointData","url"),!N)){k=void 0;break a}if(x&&(y||N)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:E,unsubscribeText:y,unsubscribeCount:G,enabled:m.enabled,signinUrl:N,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.Tb(x,"urlEndpoint","url"),l.Qp=!0,l.Ir="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.ne)(k,function(a){return!!a});
return f},I2=function(a){g.nV.call(this,a);
this.A=null;this.K=!1;this.C=null;this.o={};this.G={};this.F=this.B=null;this.L=[];a=g.Y(a);this.R=g.yN(a)||g.zN(a);this.zG=!0;this.H=0;this.J=new g.Zp(null);this.D=new g.UG(this);g.K(this,this.D);this.D.O(this.player,g.sR("creatorendscreen"),this.LN);this.D.O(this.player,"crx_creatorendscreen",this.MN);this.D.O(this.player,"resize",this.gD);this.D.O(window,"focus",this.LU);this.load();var b=g.ge("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.zf(this,function(){g.me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Yza=function(a){return a.player.getVideoData().Nc?"current":a.R?"new":"current"},J2=function(a){return"creator-endscreen-editor"===a},K2=function(a,b){g.cV(a.player,"creatorendscreen");
a.B&&(a.B.dispose(),a.B=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(a){a.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){Zza(a);c=[];var d=new g.qR(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Y(a.player).B||(a.B=new g.W({I:"div",M:"ytp-ce-shadow"}),g.eV(a.player,a.B.element,4),a.F=new g.LV(a.B,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=$za(a,e);a.o[e.id]=f;a.G[e.id]=e;g.eV(a.player,f.element,4);var k=new g.qR(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);aAa(a,f,e)}g.$U(a.player,
c);a.gD()}},Zza=function(a){var b=g.cI(),c=g.dI();
c&&b&&g.NH(c,b,[a.A.visualElement])},$za=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",ca:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-covering-image",U:L2(b)},{I:"div",M:"ytp-ce-covering-shadow-top"},{I:"a",M:"ytp-ce-covering-overlay",U:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ca:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.$p(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-video-duration",ba:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={I:"div",ca:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-covering-image",U:L2(b)},{I:"div",M:"ytp-ce-covering-shadow-top"},{I:"a",M:"ytp-ce-covering-overlay",U:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ca:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.$p(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-playlist-count",P:[{I:"div",
M:"ytp-ce-playlist-icon"},{I:"div",M:"ytp-ce-playlist-count-text",ba:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={I:"div",ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-expanding-overlay",P:[{I:"div",M:"ytp-ce-expanding-overlay-hider"},{I:"div",M:"ytp-ce-expanding-overlay-background"},{I:"div",M:"ytp-ce-expanding-overlay-content",
P:[{I:"div",M:"ytp-ce-expanding-overlay-body",P:[{I:"div",M:"ytp-ce-expanding-overlay-body-padding",P:[{I:"a",ca:["ytp-ce-channel-title","ytp-ce-link"],U:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.$p(a.J,b.title||"")},ba:b.title},b.subscribeButton?{I:"div",M:"ytp-ce-subscribe-container",P:[{I:"div",M:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",M:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{I:"div",ca:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{I:"div",M:"ytp-ce-expanding-image",U:L2(b)}]};c=new g.W(c);var d=g.Td(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.S(d,"ytp-ce-subscribe-button");if(g.Y(a.player).B){var e=null;var f=b.Nd.itct}else e="endscreen",f=null;e=new g.x_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={I:"div",ca:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.xo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-expanding-overlay",P:[{I:"div",M:"ytp-ce-expanding-overlay-hider"},{I:"div",M:"ytp-ce-expanding-overlay-background"},{I:"div",M:"ytp-ce-expanding-overlay-content",P:[{I:"div",M:"ytp-ce-expanding-overlay-body",
P:[{I:"div",M:"ytp-ce-expanding-overlay-body-padding",P:[{I:"div",M:"ytp-ce-website-title",U:{dir:g.$p(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-website-metadata",ba:b.metadata},{I:"a",ca:["ytp-ce-website-goto","ytp-ce-link"],U:{href:b.targetUrl,target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{I:"div",M:"ytp-ce-expanding-image",U:L2(b)},{I:"div",M:"ytp-ce-expanding-icon",U:bAa(b.iconUrl)}]},c=new g.W(c)}b.o&&g.S(c.element,"ytp-ce-placeholder");return c},L2=function(a){if(a.RA)var b=
a.RA.thumbnails;
return bAa(b?b[b.length-1].url:null)},bAa=function(a){return a?{style:"background-image: url("+a+")"}:{}},aAa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.X("mouseenter",(0,g.A)(a.dw,a,b,c));b.X("mouseleave",(0,g.A)(a.Tw,a,b,c));g.Y(a.player).B||b.X("click",(0,g.A)(function(a){g.S(a.element,"ytp-ce-element-hover")},a,b));
b.X("click",(0,g.A)(a.BE,a,c));b.X("keypress",(0,g.A)(a.BE,a,c));b.X("focus",(0,g.A)(function(a,b){this.dw(a,b)},a,b,c));
b.X("blur",(0,g.A)(function(a,b){this.Tw(a,b)},a,b,c));
b.X("touchstart",(0,g.A)(a.dw,a,b,c));var f=g.Vd("ytp-ce-expanding-overlay-hider",b.element);f&&b.O(f,"touchstart",function(a){g.LG(a);g.or(b.element,"ytp-ce-element-hover");g.or(b.element,"ytp-ce-force-expand")});
b.X("keydown",(0,g.A)(function(a,b){this.zG=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.A)(function(a,b,c){this.H+=c;0<this.H?(g.S(a.element,"ytp-ce-force-expand"),M2(this,b.id,!0)):(g.or(a.element,"ytp-ce-force-expand"),g.or(a.element,"ytp-ce-element-hover"),M2(this,b.id,!1))},a,b,c);
a=(0,g.A)(function(a,b){b&&(a.X("blur",function(){g.ei(b)&&this.zG&&b.focus()}),a.O(b,"focus",d),a.O(b,"blur",e))},a,b);
a(g.Vd("ytp-sb-subscribe",b.element));a(g.Vd("ytp-sb-unsubscribe",b.element));b.X("focus",d);b.X("blur",e)},M2=function(a,b,c){a.B&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.T(a.o[d].element,"ytp-ce-element-shadow-show",c)},N2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||J2(g.Y(a.player).playerStyle))c&&c();else{b=cAa(a,b);var e=0,f=!1,k=new g.U(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.ZF(b[a],d)}},O2=function(a,b,c){N2(a,b.clickUrls,c);
(a=g.dI())&&b.Qp&&g.PH(a,b.visualElement)},cAa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(dAa(b[e],c));return d},dAa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},P2=function(a){return g.Fa(a)&&a.length?a[0]:a},Q2=function(a){var b=/.+/;
return g.u(a)&&null!=b&&null!=a&&a.match(b)?a:""},R2=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},S2=function(a){return g.u(a)?a:""},T2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},U2=function(a,b){return"true"==a||"false"==a?"true"==a:b},V2=function(a,b){return g.u(a)?parseFloat(a):b},W2=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Fd(a,b,c);if(a>=b&&a<=c)return a}return e},eAa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.C)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},X2=function(a,b){if(null==a)return null;
if(g.Ga(a)){var c=[];(0,g.C)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},fAa=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.th(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},gAa=function(a){function b(a){return(0,g.ne)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},hAa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Y2=function(a){if(!a)return null;
var b=g.fd(S2(a.value));b=g.cd(b);if(!b)return null;var c=T2(a.target,iAa,"current");return null==c?null:new hAa(b,c,U2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},Z2=function(a){return a.value?a.value:null},jAa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},mAa=function(a){if(!a)return null;
var b=T2(a.type,kAa),c=T2(a.trigger,lAa),d=P2(a.url);d=Y2(d?d:null);P2(a.subscribeData);return b?new jAa(b,c,d):null},nAa=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},$2=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},a3=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.wl=c;this.B=d;this.t=e;this.D=f;this.F=k;this.G=l;this.C=m;this.A=n;this.o=p},pAa=function(a,b){if(!a)return null;
var c=V2(a.x,0),d=V2(a.y,0),e=V2(a.w,0),f=V2(a.h,0),k=eAa(a.t),l=V2(a.d,0),m=V2(a.px,0),n=V2(a.py,0),p=V2(a.scaleSlope,1),t=V2(a.scaleSlopeX,p);p=V2(a.scaleSlopeY,p);var x=T2(a.scaleDimension,oAa,"xy");return b(c,d,e,f,k,l,m,n,t,p,x)},b3=function(a,b){var c=qAa(b,rAa(a,new g.wh(a.x,a.y,a.wl,a.B),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Fd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Fd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},rAa=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=nAa(c,a.C,f);
a=$2(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.wh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},sAa=function(a){return a?pAa(a,function(a,c,d,e,f,k,l,m,n,p,t){return new a3(a,c,d,e,f,k,l,m,n,p,t)}):null},tAa=function(a,b){this.o=a;
this.A=b||null},qAa=function(a,b){var c=a.A?b3(a.A,new tAa(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Ld?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ba(c)&&(d.top+=c));return d},uAa=function(a,b,c,d,e,f,k,l,m,n,p,t,x){a3.call(this,a,b,c,d,e,l,m,n,p,t,x);
this.H=f;this.J=k},vAa=function(a){if(!a)return null;
var b=V2(a.sx,0),c=V2(a.sy,0);return pAa(a,function(a,e,f,k,l,m,n,p,t,x,y){return new uAa(a,e,f,k,l,b,c,m,n,p,t,x,y)})},wAa=function(a,b,c,d,e,f,k,l,m,n,p,t,x,y){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.B=k;this.textAlign=l;this.textSize=m;this.C=n;this.padding=p;this.effects=t;this.cornerRadius=x;this.D=y},yAa=function(a){if(!a)return null;
var b=R2(a.fgColor,"#1A1A1A"),c=R2(a.bgColor,"#FFF"),d=R2(a.borderColor,"#000"),e=W2(a.borderWidth,0,5,!1,0),f=W2(a.bgAlpha,0,1,!1,.8),k=R2(a.highlightFontColor,"#F2F2F2"),l=W2(a.highlightWidth,0,5,!1,3),m=S2(a.textAlign),n=W2(a.textSize,3.3,30.1,!0,3.6107),p=S2(a.fontWeight),t=fAa(a.padding),x=gAa(a.effects),y=W2(a.cornerRadius,0,10,!0,0);a=P2(a.gradient);if(a=a?a:null){var E=W2(a.x1,0,100,!0,0),G=W2(a.y1,0,100,!0,0),N=W2(a.x2,0,100,!0,100),O=W2(a.y2,0,100,!0,100),sa=R2(a.color1,"#FFF"),kb=R2(a.color2,
"#000");a=new xAa(E,G,N,O,sa,kb,W2(a.opacity1,0,100,!0,100),W2(a.opacity2,0,100,!0,0))}else a=null;return new wAa(b,c,d,e,f,k,l,m,n,p,t,x,y,a)},xAa=function(a,b,c,d,e,f,k,l){this.B=a;
this.D=b;this.C=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},zAa=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.B=d},BAa=function(a){if(!a)return null;
var b=T2(a.type,AAa,"rect"),c=X2(a.rectRegion,sAa),d=X2(a.anchoredRegion,vAa);a=X2(a.shapelessRegion,sAa);return new zAa(b,c,d,a)},CAa=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.B&&a.B.length?a.B[0]:null},DAa=function(a,b){this.A=a;
this.o=b},EAa=function(a,b){this.state=a;
this.ref=b},GAa=function(a){if(!a)return null;
var b=T2(a.state,FAa);a=Q2(a.ref);return b?new EAa(b,a):null},HAa=function(a,b,c,d){this.o=a||[];
this.B=b||[];this.C=c;this.A=d;this.value=!1},IAa=function(a){if(!a)return null;
var b=X2(a.condition,GAa),c=X2(a.notCondition,GAa),d=U2(a.show_delay,!1);a=U2(a.hide_delay,!1);return b||c?new HAa(b,c,d,a):null},JAa=function(a,b,c){(0,g.C)(a.o,g.La(b,!1),c);
(0,g.C)(a.B,g.La(b,!0),c)},c3=function(a,b,c,d,e,f,k,l,m,n,p,t,x,y){this.id=a;
this.author=b;this.type=c;this.style=d;this.C=e;this.segment=f;this.B=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=t;this.o=x;this.itct=y},MAa=function(a){if(!a)return null;
var b=Q2(a.id),c=Q2(a.author),d=T2(a.type,KAa),e=T2(a.style,d3),f=S2(P2(a.TEXT)),k=S2(a.data);k=0!=k.length?JSON.parse(k):{};var l=P2(a.segment);var m=l?l:null;m?(Q2(m.timeRelative),l=Q2(m.spaceRelative),l=(m=X2(m.movingRegion,BAa))?new DAa(l,m):null):l=null;m=X2(a.action,mAa);var n=X2(a.trigger,IAa),p=P2(a.appearance);(p=yAa(p?p:null))||(p=yAa({}));var t=T2(a.coordinate_system,LAa,"video_relative"),x=U2(a.closeable,!0),y=S2(a.log_data);a=S2(a.itct);return b&&d?new c3(b,c,d,e,f,l,m,n,p,t,x,k,y,a):
null},f3=function(a){return e3(a,function(a){return"click"==a.trigger})},e3=function(a,b){return(0,g.Wj)(a.B,b,void 0)},NAa=function(a,b,c){(0,g.C)(a.B,b,c)},OAa=function(a,b){return g.Qa(a.B,b,void 0)},PAa=function(a,b,c){(0,g.C)(a.G,b,c)},QAa=function(a,b){(0,g.I)(a.G,b,void 0)},g3=function(a){return(a=RAa(a))?CAa(a):null},RAa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},SAa=function(a,b){var c=g3(a);
return c&&b?$2(b,c.A,c.o?c.o:"xy"):1},UAa=function(a,b,c){this.o={};
this.B=!1;this.D="ivTrigger:"+a;this.A=c;JAa(b,function(a,b){var c=TAa(b.state,b.ref);this.A.subscribe(c,(0,g.A)(this.C,this,c,a));this.o[c]=a},this)},TAa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},h3=function(){this.o=!1;
this.D=this.A=null},i3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new D2(b,c,void 0,void 0,void 0),a.A=b,a.A.Ap(),a.D=g.ee("DIV"),b=a.A.sa(),a.D.appendChild(b));
return a.A},j3=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Jb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},k3=function(a,b){var c=":"+(g.Wv.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},VAa=function(a,b){var c=k3(a,j3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=k3(a,j3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},j3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=k3(a,j3("feComposite",{"in":c,in2:b,operator:"in"}));return k3(a,j3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},WAa=function(a,b){var c=k3(a,j3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=k3(a,j3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=k3(a,j3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=k3(a,j3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=k3(a,j3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=k3(a,j3("feComposite",{operator:"out","in":c,in2:d}));return k3(a,j3("feComposite",{operator:"over","in":b,in2:c}))},XAa=function(a,b){return b},YAa=function(a){var b=
j3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.C)(a,function(a){a:{switch(a){case "bevel":a=VAa;break a;case "dropshadow":a=WAa;break a}a=XAa}c=a(b,c)});
return b},ZAa=function(a){a=(0,g.ne)(a,function(a){return a in l3});
g.pb(a,function(a,c){return l3[a]-l3[c]});
return a},$Aa=function(a){return g.Qa(a,function(a){return"dropshadow"==a})?new g.th(0,7,7,0):new g.th(0,0,0,0)},aBa=function(a,b,c){var d=new x2;
d.moveTo(a.left+b+c,a.top+c);d.Mc(a.left+a.width-b-c,a.top+c);y2(d,b,b,-90);d.Mc(a.left+a.width-c,a.top+a.height-b-c);y2(d,b,b,0);d.Mc(a.left+b+c,a.top+a.height-c);y2(d,b,b,90);d.Mc(a.left+c,a.top+b+c);y2(d,b,b,180);d.close();return d},bBa=function(a,b,c,d){var e=a.D;
e?a=new u2(e.B*b/100,e.D*c/100,e.C*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new t2(a.bgColor,d?Math.max(b,.9):b));return a},m3=function(a,b){var c=g.xh(a);
c.expand($Aa(b));return new g.wh(c.left,c.top,c.right-c.left,c.bottom-c.top)},cBa=function(a,b,c){if(c.length&&(b=g.Td(document,"g",void 0,b),b.length)){var d=ZAa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=YAa(d),a=0<d.childNodes.length?Nza(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},n3=function(){h3.call(this);
this.C=0},dBa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},o3=function(a){h3.apply(this,arguments)},p3=function(a){h3.apply(this,arguments)},q3=function(a){n3.apply(this,arguments)},r3=function(a,b,c,d,e){g.J.call(this);
this.o=a;this.Z=b;this.F=c;this.fa=d;this.da=e;this.J=!1;this.Y=new g.RG(this);g.K(this,this.Y);this.N=this.D=this.G=this.R=this.A=null;this.aa=!1;this.ea=this.K=this.L=null;this.Cq=new g.Xl(this.uL,100,this);g.K(this,this.Cq);this.H=new g.U(this.aC,500,this);g.K(this,this.H);this.T=this.B=this.C=null},eBa=function(a,b){var c=(0,g.A)(function(a,c,f){c=f?s3(this,c,(0,g.A)(f,this)):s3(this,c);
this.Y.X(b,a,c)},a);
c("mouseover","G",a.pD);c("mouseout","F",a.Zh);c("click","D");c("touchend","D")},fBa=function(a){if(a.o.D){if(e3(a.o,function(a){return"close"==a.type}))var b=a.A;
else a.C=g.ee("DIV","annotation-close-button"),g.L(a.C,!1),g.PE(a.C,"annotation_id",a.o.id),a.A.appendChild(a.C),b=a.C;var c=function(a){a.stopPropagation()};
a.Y.X(b,"click",s3(a,"E",c));a.Y.X(b,"touchend",s3(a,"E",c))}},s3=function(a,b,c){return(0,g.A)(function(a){if(this.da)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.L(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Be(f,"annotation")){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.L(d,
!0)}}d=g.ci(a.target);a=new g.Ld(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.fa.V(b,this.o)},a)},u3=function(a){if(a.A||a.B){var b=g3(a.o);
if(b){var c=t3(a);if(a.A){b=b3(b,c);var d=g.RU(a.F).getVideoContentRect();g.ai(a.A,b.width,b.height);g.Qh(a.A,b.left,b.top);a.R=new g.wh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=g3(a.o))&&d?nAa(d,e.C,e.o?e.o:"xy"):1;var f=SAa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.th(d,d,d,d));d=new g.th(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+
d.left+"px";"label"==a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.RU(a.F).getVideoContentRect();var p=g.YU(a.F);g.yh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=gBa(a,23,b,d,e);if(a.C){var t=43-f.width;0<t&&(b.left+f.left-t>n.left&&(f.left-=t),f.width+=t)}t=f;g.ai(a.D,f.width,f.height);g.Qh(a.D,f.left,f.top)}a.C&&
(t?b=new g.Ld(t.left+t.width-23-18,a.aa?t.top+2:t.top+t.height-18-2):(t=gBa(a,18,b,d,e),b=new g.Ld(t.left,t.top),g.ai(a.C,t.width,t.height)),g.Qh(a.C,b));a.N=new g.wh(a.R.left+t.left,a.R.top+t.top,t.width,t.height);a.L=a.Y.X(g.RU(a.F),"mousemove",a.BO,a)}else a.D&&(t=e/f*d.height*4.2/100,t=new g.Nd(t,t),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,t=new g.wh(b.width-t.width-e,b.height-t.height-e,t.width,t.height)):t=new g.wh(b.width-t.width-3*d.height/100,(b.height-t.height)/2,t.width,
t.height),g.ai(a.D,t.width,t.height),g.Qh(a.D,t.left,t.top)),a.C&&(t=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Qh(a.C,t&&e?new g.Ld(b.width-9,-9):t?new g.Ld(b.width-9,45<b.height?9:b.height-9):e?new g.Ld(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Ld(45<b.width?b.width-9-18:-9,b.height-9):new g.Ld(-9,45<b.height?9:b.height-9)))}a.B&&a.B.B(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;t=g.RU(a.F).getVideoContentRect();c.style.fontSize=
360*b.textSize*SAa(a.o,t)/100+"px";t=a.o.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==t||"highlightText"==t?"center":"left";b.C&&(c.style.fontWeight=b.C);a=a.A;c=a.style.overflow;t=(b=g.Vd("annotation-link-icon",a))?g.ei(b):!1;e=(d=g.Vd("annotation-close-button",a))?g.ei(d):!1;t&&g.L(b,!1);e&&g.L(d,!1);m=f="";if(n=g.Vd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>
a.offsetWidth){l=k=Dza(a);p=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+x,k)):l=Math.max(l-x,p),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.L(d,!0);t&&g.L(b,!0)}}}},gBa=function(a,b,c,d,e){var f=0<e;
b=new g.wh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.S(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.S(a.A,"annotation-extend-up"),a.aa=!0);return b},v3=function(a){return"label"!=a.o.style||a.B.o},t3=function(a){var b=g.RU(a.F).getVideoContentRect();
if("player_relative"==a.o.F){var c=g.RU(a.F).getPlayerSize();b=new g.wh(-b.left,-b.top,c.width,c.height)}else b=new g.wh(0,0,b.width,b.height);return new tAa(b,a.T?g3(a.T):null)},hBa=function(a,b){return b?new g.wh(a.x+b.left,a.y+b.top,b.width,b.height):null},w3=function(a,b,c){g.J.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.B=this.isVisible=!1;iBa(b,a)},iBa=function(a,b){QAa(a,function(c){return new UAa(a.id,c,b)})},jBa=function(a){a.A.unsubscribe("resize",a.oD,a);
a.A.unsubscribe("onVideoAreaChange",a.gF,a)},x3=function(a){a.o&&(a.o.stop(),a.o=null)},kBa=function(a,b,c){r2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},y3=function(a,b,c){r2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.C=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=Y2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},lBa=function(a,b,c){y3.call(this,a,b,c);
this.J=b.ypc_flow_type;this.G=b.innertube_request_params},mBa=function(a,b,c){r2.call(this,a,b,c);
this.C=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},nBa=function(a,b,c){r2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.C=null;if(a=b.signin_url)this.C=Y2({target:"current",value:a});this.J=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},pBa=function(a,b,c){y3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new oBa(a[b]))},oBa=function(a){this.merchant=g.F(a.merchant);
this.price=g.F(a.price)},qBa=function(a,b,c){y3.call(this,a,b,c);
this.R=b.ypc_item_type;this.J=b.ypc_item_id;this.G=b.ypc_flow_type},rBa=function(a,b,c){r2.call(this,a,b,c);
this.C=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},z3=function(a,b,c){r2.call(this,a,b,c);
this.J=b.image_url;this.C=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=Y2({target:b.target||"new",value:b.url})},sBa=function(a){this.o=a;
this.A={}},tBa=function(a){var b={};
b=(b["iv-event"]=1,b);g.XU(a.o,"iv",b,void 0)},D3=function(a,b,c,d){if(b){var e=A3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=B3(a,"cta_annotation_shown",e,c);C3(a,e,uBa(b,d))}},E3=function(a,b,c,d,e,f){if(b){var k=A3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.ic(k,d);b=B3(a,"cta_annotation_clicked",k,e);C3(a,k,b,c,f)}},F3=function(a,b){if(b){var c=A3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=B3(a,"cta_annotation_closed",c);C3(a,c,d)}},uBa=function(a,b){return b?(0,g.I)(a,g.La(function(a,b){return g.Tn(b,a)},b)):a},B3=function(a,b,c,d){d=d?g.cb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Y(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.Xz){if((b=a.Xz[b])&&g.VJ(b)){a=g.oc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Tq){b=g.vF(a.Tq,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},C3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.C)(c||[],function(a){f++;
g.ZF(a,m)});
e&&(f++,0!=e&&a.o.sendVideoStatsEngageEvent(e,m));g.XU(a.o,"iv",b,m)},A3=function(a,b){var c={};
if(b){var d=new g.Cn(b);(0,g.C)(d.Ib(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Y(a.o).playerStyle;return c},G3=function(a,b,c,d,e){e=A3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;C3(a,e,d)},H3=function(a,b,c,d){c&&(c=A3(a,c),c["iv-event"]=b,C3(a,c,d))},vBa=function(a,b,c,d,e,f,k){this.A=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.B=k},I3=function(a,b,c){this.o=a;
this.C=b;this.D=c;this.A=new g.Zp(null)},xBa=function(a,b){var c=[];
(0,g.C)(b.choices,function(a){c.push({I:"li",M:b.G+"-"+a.index.toString(),P:[{I:"label",P:[{I:"input",M:"iv-card-poll-choice-input",U:{type:"checkbox",role:"radio",name:b.G+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{I:"span",M:"iv-card-poll-choice-text",P:[{I:"span",M:"iv-card-poll-choice-percent"},J3(this,"span",void 0,a.desc)]}]},{I:"div",M:"iv-card-poll-result",P:[{I:"div",M:"iv-card-poll-result-bar"}]}]})},a);
var d={I:"ul",U:{role:"radiogroup"},P:c},e={};b.C&&(e["aria-label"]=g.DV("$POLL_TITLE - \u6295\u7968\u3059\u308b\u306b\u306f\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{I:"div",M:"iv-card-content",P:[J3(a,"h2",e,b.title),{I:"form",P:[{I:"fieldset",P:[d]}]}]}];b.C&&(f.push("iv-card-unavailable"),d.push({I:"div",ca:["iv-card-sign-in"],P:[{I:"h2",ba:"\u30a2\u30f3\u30b1\u30fc\u30c8\u306b\u53c2\u52a0\u3059\u308b\u306b\u306f"},
{I:"a",ca:["iv-card-sign-in-button","iv-button"],U:{href:Z2(b.C)},P:[{I:"span",ca:["iv-button-content"],ba:"\u30ed\u30b0\u30a4\u30f3"}]}]}));f=new g.W({I:"div",ca:f,P:d});d=f.element;wBa(b,d);yza(a.o.A,d,g.La(a.G,b),a);(0,g.C)(g.Ud("iv-card-poll-choice-input",d),function(a){this.o.A.X(a,"focus",g.La(this.B,!0));this.o.A.X(a,"blur",g.La(this.B,!1))},a);
b.C&&(d=g.Vd("iv-card-sign-in-button",d),a.C(d,b.C,b.id,b.Nd,b.B,b.A.click,5));return f},M3=function(a,b,c,d){var e=b.displayDomain?{I:"div",
M:"iv-card-image-text",ba:b.displayDomain}:"",f=yBa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.imageUrl,e),{I:"div",M:"iv-card-content",P:[J3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({I:"div",ca:["iv-card-sign-in"],P:[J3(a,"h2",void 0,b.L||""),{I:"p",ba:b.K},{I:"a",ca:["iv-card-sign-in-button","iv-button"],U:{href:Z2(b.o)},P:[J3(a,"span","iv-button-content","\u30ed\u30b0\u30a4\u30f3")]}]});k=new g.W({I:"div",ca:k,P:e});L3(a,k,b,
c,d);return k},zBa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.C?{I:"span",ca:d,U:e,ba:b.C}:"";c={I:"div",ca:["iv-card",c],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.J,d?{I:"div",M:"iv-card-image-text",P:[d,b.priceText]}:""),{I:"div",M:"iv-card-content",P:[{I:"h2",M:"iv-card-primary-link",ba:b.title},N3(a,b)]}]}]};c=new g.W(c);L3(a,c,b);return c},O3=function(a,b){return b.customMessage?J3(a,"div",
"iv-card-message",b.customMessage):""},K3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",M:"iv-card-image",U:{style:c},P:d}},N3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.C)(b.metaInfo,function(a){c.push(J3(this,"li","",a))},a);
return{I:"ul",M:"iv-card-meta-info",P:c}},J3=function(a,b,c,d){c?g.u(c)?c={"class":c}:g.Fa(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.$p(a.A,d);return{I:b,U:c,ba:d}},yBa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.C&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.C+");");d.dir=g.$p(a.A,b.customMessage);var e=[{I:"span",ba:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({I:"span",M:"iv-card-link-icon"}));return{I:"div",ca:c,U:d,P:e}},wBa=function(a,b){var c=0;
(0,g.C)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Vd(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.T(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.Vd("iv-card-poll-choice-percent",f);g.ue(l,g.DV("$PERCENT%",{PERCENT:k}));f=g.Vd("iv-card-poll-result-bar",f);g.Jh(f,"transform","scaleX("+e.toFixed(2)+")")}g.T(b,"iv-card-poll-voted",null!=a.o);g.T(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},ABa=function(a,b,c,d){d?(c&&a.o.videoData.Fa||a.o.o.pauseVideo(),a.o.o.isFullscreen()&&a.o.o.toggleFullscreen(),E3(a.o.logger,b.B,d,void 0,b.A.click,5),(a=g.dI())&&g.PH(a,b.F)):b.url&&a.D(b.url,b.id,b.Nd,b.B,b.A.click||[],5)},L3=function(a,b,c,d,e){c.o&&BBa(a,g.Ud("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&BBa(a,g.Ud("iv-click-target",b.element),c,c.url,d)},BBa=function(a,b,c,d,e){(0,g.C)(b,function(a){if(e){var b=(0,g.A)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.o.A.X(a,"click",b)}else d&&this.C(a,d,c.id,c.Nd,c.B,c.A.click,5)},a)},CBa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},P3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=DBa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},DBa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},EBa=function(a){a=Z2(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!P3(a))||(b=g.ah(g.$g(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.tF(a);if(!b||!b.v)return null;if(b=b.t)return CBa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.rF(a[1]))&&a.t?CBa(a.t):-1},FBa=function(a){a=Z2(a);
a=a.replace(/https?:\/\//g,"");return P3(a)?(a=g.tF(a))&&a.v?a.v:null:null},GBa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},Q3=function(a,b){return b?b:P3(a)?"current":"new"},R3=function(a,b){g.J.call(this);
this.Ea=a;this.context=b;this.zy=!1;this.fa=0},HBa=function(a){return(0,g.H)()-a.fa},IBa=function(a,b,c,d,e,f){var k=Z2(b);
if(k){var l=Q3(k,b.target),m=(0,g.A)(function(){b.o&&this.context.o.pauseVideo();var a=this.context.videoData.Nc||!1,d=g.tF(k||"");a&&d&&(d.v||d.list)?g.L0(this.context.o.app,d.v,c,d.list,!1,void 0,void 0):g.AV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=HBa(a);E3(a.context.logger,d,m,n,e,f);P3(k)||(a=g.dI(),d=c.itct,a&&d&&g.PH(a,g.LH(d)))}},U3=function(a,b,c){R3.call(this,b,c);
var d=this;this.A=a;this.Z=null;this.aa=this.Aa=this.D=this.za=!1;this.ea=null;this.N=new g.U(g.z,c.D.wd?4E3:3E3);g.K(this,this.N);this.na=new g.U(g.z);g.K(this,this.na);this.F=new I3(c,(0,g.A)(this.fl,this),(0,g.A)(this.Zp,this));this.J=new g.W({I:"div",M:"iv-drawer",U:{id:"iv-drawer"},P:[{I:"div",M:"iv-drawer-header",U:{"aria-role":"heading"},P:[{I:"span",M:"iv-drawer-header-text"},{I:"button",ca:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"\u30ab\u30fc\u30c9\u3092\u9589\u3058\u308b",
tabindex:"0"}}]},{I:"div",M:"iv-drawer-content"}]});g.K(this,this.J);this.G=this.J.element;this.ia=new g.LV(this.J,330);g.K(this,this.ia);this.Ba=g.Vd("iv-drawer-header-text",this.G);this.C=g.Vd("iv-drawer-content",this.G);this.B=[];this.ua=this.T=this.H=this.da=this.o=null;this.L=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&S3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.D)&&T3(d)});
this.R=this.K=this.ha=null},OBa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&JBa[c]){c=new JBa[c](b.id,b.data,b.o);if(!a.za){g.nr(a.sa(),["html5-stop-propagation","iv-drawer-manager"]);g.eV(a.A,a.G,5);KBa(a);a.T=g.Vd("ytp-cards-button",a.A.getRootNode());var d=g.Vd("iv-drawer-close-button",a.G);a.ua=d;a.za=!0}LBa(a,c.id);var e=MBa(a,c);if(e){d={oc:c,Mt:e.element,NC:!1};var f=NBa(a,d);g.gb(a.B,f,0,d);e.ya(a.C,f);a.Jo();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.La(a.KV,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.bG(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.La(a.bG,d)),V3(a))}}},PBa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){S3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){T3(a)});
var c=b.data.headerText;g.ue(a.Ba,c);a.T&&a.T.setAttribute("title",c);b.data.eventId&&(a.Z=b.data.eventId);a.ha=g.LH(b.data.trackingParams);a.R=g.LH(b.data.closeTrackingParams);a.K=g.LH(b.data.iconTrackingParams)},LBa=function(a,b){var c=QBa(a,b);
c&&(c==a.o&&(a.o=null),a.A.removeCueRange(c.oc.id),g.me(c.Mt),g.Za(a.B,c),a.Jo(),V3(a))},S3=function(a,b,c,d){if(!a.D){a.ia.show();
a.da=new g.U(function(){g.S(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.da.start();a.ea=g.FG(a.C,"mousewheel",(0,g.A)(a.dO,a));a.D=!0;a.fa=(0,g.H)();G3(a.context.logger,a.Z,7,void 0,d&&d.oc?d.oc.B:void 0);var e=g.dI();e&&a.ha&&a.R&&p2(e,[a.ha,a.R]);var f={TRIGGER_TYPE:b};(0,g.C)(a.B,function(b){b.NC||(b.NC=!0,D3(a.context.logger,b.oc.B,b.oc.A.PM,f));e&&p2(e,[b.oc.F])});
h2(a.A);c&&(a.H=new g.U(function(){a.ka=a.T;a.ua.focus()},330),a.H.start())}},T3=function(a){a.D&&(a.ia.hide(),g.GG(a.ea),a.ea=null,g.or(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,h2(a.A),a.H&&a.H.stop(),a.H=new g.U(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},KBa=function(a){var b=g.Vd("iv-drawer-close-button",a.G);
a.context.A.X(b,"click",a.lK,a);a.context.A.X(a.C,"touchend",function(){a.N.start()});
a.context.A.X(a.C,"scroll",a.xK,a);a.context.B.subscribe("onHideControls",function(){a.aa=!0});
a.context.B.subscribe("onShowControls",function(){a.aa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.aa=g.mr(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.ZE("iv-button-shown",a.kN,a));a.L.push(g.ZE("iv-button-hidden",a.jN,a));a.L.push(g.ZE("iv-teaser-shown",a.nN,a));a.L.push(g.ZE("iv-teaser-hidden",a.mN,a));a.L.push(g.ZE("iv-teaser-clicked",a.lN,a))},MBa=function(a,b){switch(b.type){case "simple":return M3(a.F,b);
case "collaborator":var c=a.F,d={I:"div",ca:["iv-card","iv-card-channel"],P:[{I:"a",ca:["iv-click-target"],U:{href:Z2(b.url),"data-ytid":b.channelId},P:[K3(b.profileImageUrl),{I:"div",M:"iv-card-content",P:[O3(c,b),{I:"h2",M:"iv-card-primary-link",ba:b.title},N3(c,b)]}]}]};d=new g.W(d);L3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.A)(c.F,c,b),M3(c,b,d,d);case "episode":return zBa(a.F,b,"iv-card-episode");case "movie":return zBa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={I:"div",
ca:["iv-card","iv-card-playlist"],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.C,{I:"div",M:"iv-card-image-overlay",P:[{I:"span",M:"iv-card-playlist-video-count",ba:b.playlistVideoCount.toString()}]}),{I:"div",M:"iv-card-content",P:[O3(c,b),J3(c,"h2","iv-card-primary-link",b.title),N3(c,b)]}]}]},d=new g.W(d),L3(c,d,b),d;case "poll":return xBa(a.F,b);case "productListing":c=a.F;var e=!g.Va(b.offers);d=["iv-card"];var f="",k=yBa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",
e=b.offers[0],k=[],e.price&&k.push({I:"div",M:"iv-card-offer-price",ba:e.price}),e.merchant&&k.push({I:"div",M:"iv-card-offer-merchant",ba:e.merchant}),k={I:"div",P:k});d={I:"div",ca:d,U:{tabindex:"0"},P:[{I:"a",ca:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+b.imageUrl+");",href:Z2(b.url),"aria-hidden":"true",tabindex:"-1"}},{I:"div",M:"iv-card-content",P:[b.sponsored?{I:"div",M:"iv-card-sponsored",P:["\u30b9\u30dd\u30f3\u30b5\u30fc\u63d0\u4f9b",{I:"div",M:"iv-ad-info-container",
P:[{I:"div",M:"iv-ad-info",ba:"{{adInfo}}"},{I:"div",M:"iv-ad-info-icon-container",P:[{I:"div",M:"iv-ad-info-icon"},{I:"div",M:"iv-ad-info-callout"}]}]}]}:"",{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[J3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.ge("span");g.ue(f,"\u3053\u306e\u52d5\u753b\u306b\u95a2\u9023\u3057\u3066\u3044\u308b\u3068\u601d\u308f\u308c\u308b\u5546\u54c1\u3092\u8868\u793a\u3057\u3066\u3044\u307e\u3059\u3002Google \u306f\u8ca9\u58f2\u8005\u304b\u3089\u652f\u6255\u3044\u3092\u53d7\u3051\u3066\u3044\u308b\u3053\u3068\u304c\u3042\u308a\u307e\u3059\u3002");
d.Nb(f,"adInfo");L3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.A)(c.H,c,b),M3(c,b,d,d);case "video":return c=a.F,d=b.isLiveNow?{I:"span",ca:["yt-badge","yt-badge-live"],ba:"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d"}:"",d={I:"div",ca:["iv-card","iv-card-video"],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.C,b.videoDuration?{I:"span",M:"iv-card-video-duration",ba:b.videoDuration}:""),{I:"div",M:"iv-card-content",P:[O3(c,b),J3(c,"h2","iv-card-primary-link",b.title),N3(c,b),d]}]}]},d=new g.W(d),
L3(c,d,b),d}return null},NBa=function(a,b){if(0==a.B.length)return 0;
var c=g.Ra(a.B,function(a){return b.oc.startMs>a.oc.startMs||b.oc.startMs==a.oc.startMs&&b.oc.timestamp>=a.oc.timestamp?!0:!1});
return-1==c?0:c+1},RBa=function(a){return a.o?"productListing"==a.o.oc.type:(0,g.cn)(a.B,function(a){return"productListing"==a.oc.type})},V3=function(a){g.T(a.A.getRootNode(),"ytp-cards-shopping-active",RBa(a))},SBa=function(a,b){if(a.J.A){var c=new m2([0,
a.C.scrollTop],[0,b.Mt.offsetTop],600,Lza);a.context.C.X(c,"animate",function(b){a.C.scrollTop=b.y});
a.context.C.X(c,"finish",function(b){a.C.scrollTop=b.y});
c.play()}else g.pQ(a.J,!0),a.C.scrollTop=b.Mt.offsetTop,g.pQ(a.J,!1)},W3=function(a){return a.o&&a.o.oc?a.o.oc:a.B[0]&&a.B[0].oc?a.B[0].oc:null},QBa=function(a,b){return g.Qa(a.B,function(a){return a.oc.id==b})},X3=function(a,b,c){R3.call(this,a,b);
this.annotation=c;this.isActive=!1},TBa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Y3=function(a,b,c){X3.call(this,a,b,c);
this.A=null;this.G=!1;this.B=null;this.C=!1;this.H=0;this.o=this.F=this.D=null},Z3=function(a,b,c){X3.call(this,a,b,c);
this.J=this.D=this.K=!1;this.G=5E3;this.C=null;this.H=g.ee("DIV","iv-promo-contents");this.A=this.B=this.o=null;this.F=new g.U(function(){this.o.setAttribute("aria-hidden",!0);g.L(this.B,!1);g.L(this.A,!0)},700,this);
g.K(this,this.F)},UBa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.sa().setAttribute("aria-hidden",!0);a.sa().setAttribute("aria-label","\u30d7\u30ed\u30e2\u30fc\u30b7\u30e7\u30f3");a.sa().tabIndex=0;var e=a.annotation.ab(),f=b.image_url;if(f){var k=g.ee("DIV",["iv-promo-img","iv-click-target"]);f=g.ee("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=
g.ee("SPAN","iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ee("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.fl(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.ee("A","iv-promo-txt"),g.Bd(f,Z2(e)),a.o=f):a.o=g.ee("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ee("P",null,g.ee("STRONG",null,b.text_line_1));var m=g.ee("P",null,g.ee("SPAN","iv-promo-link",b.text_line_2));
if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");a.context.D.experiments.o("web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ee("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ee("BUTTON",["iv-button","iv-promo-button"],g.ee("SPAN","iv-button-content",f));var p=g.ee("DIV","iv-promo-button-container");p.appendChild(f);e&&a.fl(a.sa(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.S(a.o,"iv-click-target");e&&a.fl(a.o,e,a.annotation.id,
b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=g.ee("P",null,g.ee("SPAN",null,b.text_line_1)),m=g.ee("P",null,g.ee("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ee("SPAN",["yt-badge","iv-promo-badge-live"],"\u30e9\u30a4\u30d6\u914d\u4fe1\u4e2d")),g.S(a.o,"iv-click-target"),e&&a.fl(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.ee("DIV",
"iv-promo-actions");a.A=g.ee("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="\u62e1\u5927";a.context.A.X(a.A,"click",g.La(a.Ku,5E3),a);c.appendChild(a.A);g.L(a.A,!1);a.context.A.X(a.sa(),"mouseover",a.wL,a);a.context.A.X(a.sa(),"mouseout",a.vL,a);a.context.A.X(a.sa(),"touchend",g.La(a.Ku,5E3),a);a.B=g.ee("BUTTON",["iv-promo-close","ytp-button"]);a.B.title="\u9589\u3058\u308b";a.context.A.X(a.B,"click","cta"==a.annotation.style&&b.text_line_3?a.lL:a.CO,a);c.appendChild(a.B);g.nr(a.sa(),d);k&&
(a.sa().appendChild(k),n&&k.appendChild(n));a.sa().appendChild(a.H);a.sa().appendChild(c)},VBa=function(a){a.D||a.J||a.C||(g.S(a.sa(),"iv-promo-collapsed"),a.D=!0,a.F.start())},WBa=function(a){a.F.stop();
a.D&&(g.pr(a.sa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.L(a.A,!1),g.L(a.B,!0))},XBa=function(a,b){a.C||(a.C=g.Pg(function(){$3(this);
VBa(this)},b,a))},$3=function(a){a.C&&(g.Qg(a.C),a.C=null)},a4=function(a){g.nV.call(this,a);
this.K=!1;this.J=0;this.A={};this.L={};this.ob=new sBa(a);this.G=new g.UG(this);g.K(this,this.G);this.F=this.B=null;this.G.O(this.player,"onVideoAreaChange",(0,g.A)(this.V,this,"onVideoAreaChange"));this.G.O(this.player,"onHideControls",(0,g.A)(this.V,this,"onHideControls"));this.G.O(this.player,"onShowControls",(0,g.A)(this.V,this,"onShowControls"));this.G.O(this.player,"resize",(0,g.A)(this.V,this,"resize"));this.G.O(this.player,"presentingplayerstatechange",(0,g.A)(this.V,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.LR,this);this.subscribe("onShowControls",this.TT,this);this.subscribe("presentingplayerstatechange",this.YS,this);this.subscribe("resize",this.Uw,this);this.subscribe("G",this.JN,this);this.subscribe("F",this.Zh,this);this.subscribe("D",this.tQ,this);this.subscribe("E",this.ZQ,this);g.Y(this.player).J.subscribe("vast_info_card_add",this.fF,this);this.T=new g.UG(this);g.K(this,this.T);this.T.O(this.player,g.sR("annotations_module"),this.HN);this.T.O(this.player,
"crx_annotations_module",this.IN);this.N=g.ee("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.ee("DIV","video-custom-annotations");this.D=new g.W({I:"div",ca:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.D);g.eV(this.player,this.D.element,4);this.D.hide();this.C=new g.W({I:"div",ca:["ytp-iv-video-content"]});g.K(this,this.C);g.ie(this.C.element,g.ee("DIV","video-annotations",this.N,this.Z));this.H=this.o=null;this.R=[];YBa(this)&&this.load();var b=g.ge("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.zf(this,function(){g.me(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ZBa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},YBa=function(a){var b=g.Y(a.player);
a=a.player.getVideoData();return 1==(b.nh||a.nh)&&!a.xl||null!==b.J.get(a.videoId)},$Ba=function(a,b,c){a.K=!0;
a.F=g.DF(b,c)},aCa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(aCa(a,e))}return c},bCa=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},dCa=function(a,b){var c=cCa(a,b);
if(!c&&"marker"!=b.type)return null;PAa(b,function(a){a=(0,g.A)(this.rU,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new w3(a.ia,b,c);g.K(d,c);return d},eCa=function(a,b){var c=g.ee("DIV",["annotation",
"annotation-type-custom"]);g.L(c,!1);var d=null;switch(b.type){case "branding":if(g.Y(a.player).rd)break;a.D.element.appendChild(c);d=new Y3(c,b4(a),b);break;case "promotion":g.eV(a.player,c,4),d=new Z3(c,b4(a),b)}d&&d.Ar();return d},hCa=function(a){var b=a.player.getVideoData();
if(b.te){var c=g.Y(a.player),d=c.J.get(b.videoId);if(d){var e={format:"XML",hd:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.hd.gaming="1");e.Ld=(0,g.A)(function(a,b,c){bCa(this,a,b)||(a=g.oF(c)&&c.responseXML?c.responseXML:null)&&c4(this,a)},a,a.J,b.videoId);
g.vH()&&(e.Ld=fCa(a,e.Ld));e.Sb={ic_only:"1"};gCa(e,d);a.K=!0;g.DF(b.te,e)}}},gCa=function(a,b){a.method="POST";
a.Sb=a.Sb||{};b.Lt&&(a.Sb.ic_coll=b.Lt);b.wi&&(a.Sb.ic_xml=b.wi);b.ol&&(a.Sb.ic_track=b.ol)},iCa=function(a){var b=new g.W({I:"div"});
g.L(b.element,!1);var c=new U3(a.player,b.element,b4(a));g.K(c,b);b.ya(a.D.element);c.Ar();return c},b4=function(a){if(!a.H){var b=new g.RG(a);
g.K(a,b);var c=new g.Ln(a);g.K(a,c);a.H=new vBa(b,c,g.Y(a.player),a.player.getVideoData(),a.ob,a.player,a.ia)}return a.H},c4=function(a,b){var c=!1;
jCa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=aCa(a,d[e]),k=null;try{k=MAa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=eCa(a,k))g.K(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=iCa(a),g.K(a,a.o)),"card"==k.type?OBa(a.o,k):PBa(a.o,k),c=!0;else if(f=dCa(a,k))g.K(a,f),a.A[k.id]=f}}c&&(h2(a.player),a.Uw());g.Jb(a.A,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.A&&
(b=this.A[b.segment.A])&&(a.T=b.annotation)}},a)},jCa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.dI();
if(b){var c=g.cI();c&&g.NH(b,c,[g.LH(a)])}}},lCa=function(a,b,c,d){d?kCa(a,b,c):d4(a,b,c)},d4=function(a,b,c){if(b=a.A[b])x3(b),c&&c.A?(a=(0,g.A)(a.ZB,a,b),b.o=new g.U(a,2E3),b.o.start()):a.ZB(b)},kCa=function(a,b,c){if(b=a.A[b])x3(b),c&&c.C?(a=(0,g.A)(a.qG,a,b),b.o=new g.U(a,2E3),b.o.start()):a.qG(b)},mCa=function(a,b){var c=a.player.getVideoData();
if(!c.Do)return!1;var d=Z2(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!P3(d))return!1;d=g.tF(d);return d.list||d.p?!1:(d=FBa(b))?c.videoId==d?!0:"new"!=b.target&&g.Y(a.player).o?!0:!1:!1},cCa=function(a,b){if(nCa(b)){var c=b.D||e3(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new r3(b,(0,g.A)(a.N.appendChild,a.N),a.player,a.ia,c)}return null},nCa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in d3)if(a.style==d3[b])return!0;return!1},e4=function(a,b,c,d){a.V(TAa(b,d),c,d)},fCa=function(a,b){return(0,g.A)(function(){if(!this.ma()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.La.apply(window,a);this.R.push(g.tH(b))}},a)};
g.MU.prototype.bl=g.ca(13,function(a,b){var c=g.NU(this).C;c&&c.bl(a,b)});
var Aza=/[^\d]+$/,Bza={cm:1,"in":1,mm:1,pc:1,pt:1},Cza={em:1,ex:1};i2.prototype.clone=function(){return new i2(this.start,this.end)};
i2.prototype.getLength=function(){return this.end-this.start};
var j2={},k2=null;g.B(Iza,g.Cf);g.B(m2,g.zu);g.h=m2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.ub())return!1;l2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.Eq();this.Oe("play");-1==this.o&&this.Oe("resume");this.o=1;var b=g.Ka(this);b in j2||(j2[b]=this);Gza();Hza(this,a);return!0};
g.h.stop=function(a){l2(this);this.o=0;a&&(this.progress=1);Jza(this,this.progress);this.Oe("stop");this.Dn()};
g.h.pause=function(){this.ub()&&(l2(this),this.o=-1,this.Oe("pause"))};
g.h.W=function(){0==this.o||this.stop(!1);this.Oe("destroy");m2.ga.W.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Lw=function(){this.Oe("animate")};
g.h.Oe=function(a){this.dispatchEvent(new Iza(a,this))};
g.B(n2,m2);n2.prototype.B=g.z;n2.prototype.Lw=function(){this.B();n2.ga.Lw.call(this)};
n2.prototype.Dn=function(){this.B();n2.ga.Dn.call(this)};
n2.prototype.Eq=function(){this.B();n2.ga.Eq.call(this)};
g.B(o2,n2);o2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.B(s2,g.dg);g.h=s2.prototype;g.h.Fu=null;g.h.Gm=null;g.h.sa=function(){return this.Gm};
g.h.addEventListener=function(a,b,c,d){g.Pf(this.Gm,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Xf(this.Gm,a,b,c,d)};
g.h.W=function(){s2.ga.W.call(this);var a=this.Gm;if(a)if(g.If(a))a.Pe&&g.Mf(a.Pe);else if(a=g.Sf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Zf(d[e])&&++b}};g.B(w2,s2);w2.prototype.fill=null;g.B(Pza,s2);x2.prototype.Pf=null;x2.prototype.ie=null;x2.prototype.Sn=!0;var Qza=[2,2,6,6,0];g.h=x2.prototype;g.h.clear=function(){this.wb.length=0;this.Ra.length=0;this.Le.length=0;delete this.Pf;delete this.ie;delete this.Sn;return this};
g.h.moveTo=function(a,b){0==g.Oa(this.wb)?this.Le.length-=2:(this.wb.push(0),this.Ra.push(1));this.Le.push(a,b);this.ie=this.Pf=[a,b];return this};
g.h.Mc=function(a){var b=g.Oa(this.wb);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.wb.push(1),this.Ra.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Le.push(c,d)}this.Ra[this.Ra.length-1]+=b/2;this.ie=[c,d]};
g.h.close=function(){var a=g.Oa(this.wb);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.wb.push(4),this.Ra.push(1),this.ie=this.Pf);return this};
g.h.clone=function(){var a=new this.constructor;a.wb=this.wb.concat();a.Ra=this.Ra.concat();a.Le=this.Le.concat();a.Pf=this.Pf&&this.Pf.concat();a.ie=this.ie&&this.ie.concat();a.Sn=this.Sn;return a};
g.h.transform=function(a){if(!this.Sn)throw Error("Non-simple path");a.transform(this.Le,0,this.Le,0,this.Le.length/2);this.Pf&&a.transform(this.Pf,0,this.Pf,0,1);this.ie&&this.Pf!=this.ie&&a.transform(this.ie,0,this.ie,0,1);return this};
g.h.isEmpty=function(){return 0==this.wb.length};g.B(Sza,w2);z2.prototype.Za=function(){return this.A};g.B(A2,g.Xv);A2.prototype.B=null;A2.prototype.Xj=function(){return this.cf?g.bi(this.sa()):g.Ba(this.width)&&g.Ba(this.height)?new g.Nd(this.width,this.height):null};
A2.prototype.resume=function(){};g.B(Tza,s2);g.B(u2,Oza);g.B(t2,Oza);g.B(B2,Pza);B2.prototype.clear=function(){g.ke(this.sa())};
B2.prototype.setSize=function(a,b){E2(this.sa(),{width:a,height:b})};
g.B(Uza,Sza);g.B(C2,Tza);C2.prototype.setSize=function(a,b){E2(this.sa(),{width:a,height:b})};var G2;g.B(D2,A2);var Wza=0;g.h=D2.prototype;g.h.Ap=function(){var a=v2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=v2(this,"g");this.H=v2(this,"defs");this.B=new B2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.C&&(this.sa().setAttribute("preserveAspectRatio","none"),this.N?this.Qr():this.sa().setAttribute("viewBox","0 0 "+(this.C?this.C+" "+this.R:"")))};
g.h.Qr=function(){if(this.cf){var a=this.Xj();if(0==a.width)this.sa().style.visibility="hidden";else{this.sa().style.visibility="";var b=a.width/this.C;a=a.height/this.R;this.B.sa().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.ai(this.sa(),a,b)};
g.h.Xj=function(){if(!g.Lh)return this.cf?g.bi(this.sa()):D2.ga.Xj.call(this);var a=this.width,b=this.height,c=g.u(a)&&-1!=a.indexOf("%"),d=g.u(b)&&-1!=b.indexOf("%");if(!this.cf&&(c||d))return null;if(c){var e=this.sa().parentNode;var f=g.bi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.sa().parentNode,f=f||g.bi(e),b=parseFloat(b)*f.height/100);return new g.Nd(a,b)};
g.h.clear=function(){this.B.clear();g.ke(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=v2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new C2(a,this);(f||this.B).sa().appendChild(e.sa());return e};
g.h.Pj=function(){var a=this.Xj();D2.ga.Pj.call(this);a||this.dispatchEvent("resize");if(this.N){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.X(Xza(),"tick",this.Qr);this.Qr()}};
g.h.im=function(){D2.ga.im.call(this);this.N&&this.K.Ma(Xza(),"tick",this.Qr)};
g.h.W=function(){delete this.A;delete this.H;delete this.B;this.K.dispose();delete this.K;D2.ga.W.call(this)};g.r(I2,g.nV);g.h=I2.prototype;
g.h.load=function(){g.nV.prototype.load.call(this);if(!J2(g.Y(this.player).playerStyle)){var a=g.fna(this.player.getVideoData());if(a)a=H2(a,Yza(this)),K2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.C&&this.C.abort();a={method:"POST",Ld:(0,g.A)(this.yR,this,a),hd:{v:a},withCredentials:!0};"gaming"==g.Y(this.player).playerStyle&&(a.hd.gaming="1");this.R&&(a.hd.ptype="embedded");var c=this.player.getVideoData().ZA;c&&(a.Sb={ad_tracking:c});if(b=g.ena(b))if(b=g.fd(b),b=g.cd(b))this.C=
g.DF(b,a)}}};
g.h.unload=function(){K2(this,null);this.C&&(this.C.abort(),this.C=null);g.nV.prototype.unload.call(this)};
g.h.Kc=function(a,b){if(!J2(g.Y(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=H2(b,"new");K2(this,c);return!0}return null};
g.h.getOptions=function(){return J2(g.Y(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.yR=function(a,b){var c=this.C=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=H2(c,Yza(this)))}K2(this,c)};
g.h.gD=function(){if(this.A&&this.A.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<oCa.length;f++){var k=Math.abs(b.width-oCa[f]);if(-1==e||d>=k)e=f,d=k}d=pCa[e];this.B&&g.Jh(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.ai(e.element,Math.round(k.width*a.width),f);g.Qh(e.element,m,n);g.pr(e.element,qCa);m=k.left+k.width/2;k=k.top+l/2;g.S(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.pr(e.element,pCa);g.S(e.element,d);(e=g.Td(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Jh(e,"height",f+"px")}}}}};
g.h.LN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.getPlayerState()?(g.UU(this.player,!0),this.player.seekTo(Infinity),this.K=!0):(N2(this,this.A.impressionUrls),(a=g.dI())&&g.OH(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.S(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.S(b,"ytp-ce-shown");N2(this,c.impressionUrls);(b=g.dI())&&g.OH(b,c.visualElement);
g.Y(this.player).Qb&&this.player.Ca("endscreenelementshown",a)}};
g.h.MN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.or(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.or(b,"ytp-ce-shown");g.Y(this.player).Qb&&this.player.Ca("endscreenelementhidden",a)}};
g.h.LU=function(a){var b=this;a.target===window&&(new g.U(function(){for(var a in b.o)g.pr(b.o[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.BE=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.mr(c,"ytp-ce-element");){g.mr(c,"subscribe-label")&&O2(this,a);if(g.mr(c,"ytp-ce-channel-subscribe"))return;c=g.re(c)}if(!c||g.mr(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Tw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Ir?(O2(this,a),this.TF(),this.player.pauseVideo(),c=g.fd(a.targetUrl),c=g.cd(c),g.AV(c,void 0,a.Nd)):(c=this.player.getVideoData().Nc,
c=(0,g.A)(this.TV,this,c,a.targetUrl,a.Nd),c=(0,g.A)(this.TF,this,c),O2(this,a,c))}}};
g.h.TV=function(a,b,c){var d=g.tF(b);a&&d&&(d.v||d.list)?g.L0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.zV(b,c)};
g.h.dw=function(a,b){g.mr(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.S(a.element,"ytp-ce-element-hover"):g.Y(this.player).B?(new g.U(function(){g.S(a.element,"ytp-ce-element-hover")},200)).start():g.S(a.element,"ytp-ce-element-hover"),N2(this,b.bM),M2(this,b.id,!0))};
g.h.Tw=function(a,b){g.or(a.element,"ytp-ce-element-hover");g.or(a.element,"ytp-ce-force-expand");M2(this,b.id,!1)};
g.h.TF=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var oCa=[346,426,470,506,570,640,853,1280,1920],pCa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),qCa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var iAa={mZ:"current",t1:"new"};var kAa={CLOSE:"close",z1:"openUrl",xJ:"subscribe"},lAa={Ls:"click",CLOSE:"close",E_:"hidden",u2:"rollOut",qJ:"rollOver",sJ:"shown"};var oAa={t4:"xx",u4:"xy",A4:"yx",B4:"yy"};g.r(uAa,a3);var AAa={YH:"anchored",g2:"rect",J2:"shapeless"};var FAa={CLOSED:"closed",H1:"playerControlShow",qJ:"rollOver",sJ:"shown"};c3.prototype.ab=function(){var a=OAa(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
c3.prototype.showLinkIcon=function(){return e3(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var d3={YH:"anchored",bI:"branding",CHANNEL:"channel",lZ:"cta",H_:"highlightText",k0:"label",PLAYLIST:"playlist",T1:"popup",X2:"speech",xJ:"subscribe",x3:"title",VIDEO:"video",n4:"website"},KAa={bI:"branding",HY:"card",PZ:"drawer",G_:"highlight",F0:"marker",Z1:"promotion",TEXT:"text",q4:"widget"},LAa={e4:"video_relative",I1:"player_relative"};UAa.prototype.C=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Ob(this.o,function(a){return a});
this.B!=a&&(this.B=a,this.A.V(this.D,a,d))};h3.prototype.sa=function(){return this.D};
h3.prototype.B=function(){};var l3={bevel:1,dropshadow:2};g.r(n3,h3);
n3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=RAa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.zh(qAa(b,rAa(e,new g.wh(e.H,e.J,e.wl,e.B),b.o))),k=d.clone();c=new g.wh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=m3(k,c.effects);l=i3(this,k.width,k.height);m=bBa(c,k.width,k.height,
this.o);d=new g.wh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Ld(f.x-k.left,f.y-k.top);this.C=17*$2(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&f3(a),t=p?f.borderWidth+1:f.borderWidth;p=(f=t?new z2(t,p?f.A:f.borderColor):null)?f.Za()/2:0;t=dBa(d,n);var x=this.F(d,e,n,t),y=n.x;n=n.y;var E=d.width,G=d.height,N=d.left;d=d.top;var O=new x2;O.moveTo(N+e+p,d+p);"t"==t&&(O.Mc(x.start,d+p),O.Mc(y,n),O.Mc(x.end,d+p));O.Mc(N+E-e-p,d+p);y2(O,e,e,-90);"r"==t&&(O.Mc(N+E-p,x.start),
O.Mc(y,n),O.Mc(N+E-p,x.end));O.Mc(N+E-p,d+G-e-p);y2(O,e,e,0);"b"==t&&(O.Mc(x.end,d+G-p),O.Mc(y,n),O.Mc(x.start,d+G-p));O.Mc(N+e+p,d+G-p);y2(O,e,e,90);"l"==t&&(O.Mc(N+p,x.end),O.Mc(y,n),O.Mc(N+p,x.start));O.Mc(N+p,d+e+p);y2(O,e,e,180);O.close();F2(l,O,f,m);if(m=this.sa())g.S(m,"annotation-shape"),g.S(m,"annotation-speech-shape"),g.Qh(m,k.left,k.top),g.ai(m,k.width,k.height),cBa(l,m,c.effects)}}}};
n3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Fd(c-a/2,d+b,d+e-a-b);return new i2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new i2(0,0)};g.r(o3,h3);o3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=m3(d,e.effects);var f=i3(this,c.width,c.height),k=new g.wh(0,0,d.width,d.height),l=e.cornerRadius;d=new z2(!e.B&&this.o?1:e.B,e.bgColor);var m=new t2("#000",0),n=d?d.Za()/2+1:0;k=aBa(k,l,n);F2(f,k,d,m);f=this.sa();g.S(f,"annotation-shape");e=e.o;g.di(f,this.o?Math.max(e,.9):e);g.Qh(f,c.left,c.top);g.ai(f,c.width,c.height)}}};g.r(p3,h3);
p3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=m3(d,c.effects),f=i3(this,e.width,e.height),k=new g.wh(0,0,d.width,d.height);d=bBa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&f3(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new z2(p,n?m.A:m.borderColor):null)?m.Za()/2+1:0;k=aBa(k,l,n);F2(f,k,m,d);if(k=this.sa())g.S(k,"annotation-shape"),g.S(k,"annotation-popup-shape"),g.Qh(k,e.left,e.top),g.ai(k,e.width,e.height),cBa(f,
k,c.effects)}}};g.r(q3,n3);q3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new i2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new i2(0,0)};g.r(r3,g.J);g.h=r3.prototype;g.h.pD=function(){this.J||(this.C&&g.L(this.C,!0),this.D&&g.L(this.D,!0),this.B&&(this.B.o=!0,g.di(this.A,v3(this)?1:0),this.B.B(this.o,t3(this))),this.H.isActive()&&this.H.stop(),this.J=!0,this.K=this.Y.Qh(g.RU(this.F),"mouseleave",function(a){this.Cq.stop();this.Zh(a)}))};
g.h.Zh=function(){this.J&&(this.N?this.H.start():this.aC(),this.B&&(this.B.o=!1,g.di(this.A,v3(this)?1:0),this.B.B(this.o,t3(this))),this.J=!1,this.K&&(this.Y.Ma(this.K),this.K=null))};
g.h.aC=function(){this.C&&g.L(this.C,!1);this.D&&g.L(this.D,!1)};
g.h.BO=function(a){this.ea=a;this.Cq.Em()};
g.h.uL=function(){var a=this.ea,b=new g.Ld(a.clientX,a.clientY),c=g.Uh(this.F.getRootNode()),d=hBa(c,this.R);c=(this.D&&g.ei(this.D)||this.C&&g.ei(this.C))&&hBa(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.pD(a):this.Zh(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.B;var b=!this.A;if(a){var c=t3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new o3:"popup"==this.o.style?d=new p3:"anchored"==this.o.style?d=new n3:"speech"==this.o.style&&(d=new q3);d&&(d.B(this.o,c),this.B=d,c=d.sa())&&(g.L(c,!1),g.S(c,"annotation-type-"+this.o.type.toLowerCase()),this.Z(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.ee("DIV",c);g.L(this.A,!1);this.o.C&&(this.G=g.ee("DIV","inner-text"),"label"==this.o.style&&(g.S(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.ue(this.G,this.o.C),this.A.appendChild(this.G));g.PE(this.A,"annotation_id",this.o.id);this.Z(this.A);eBa(this,this.A);if(f3(this.o)&&this.o.showLinkIcon()){if(d=this.o.ab())c=this.A,d=new g.vn(Z2(d)),c.title=d.A+d.B;this.D=g.ee("SPAN","annotation-link-icon");g.L(this.D,
!1);this.A.appendChild(this.D)}fBa(this);f3(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=CAa(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.B&&this.B.sa()&&(this.B.sa().style.zIndex=a)}g.L(this.A,!0);g.di(this.A,v3(this)?1:0);u3(this);this.B&&this.B.sa()&&g.L(this.B.sa(),!0)};
g.h.hide=function(){this.A&&g.L(this.A,!1);this.B&&this.B.sa()&&g.L(this.B.sa(),!1);this.L&&(this.Y.Ma(this.L),this.L=null)};g.r(w3,g.J);g.h=w3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(jBa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.oD,this),this.A.subscribe("onVideoAreaChange",this.gF,this))};
g.h.destroy=function(){if(this.view){jBa(this);var a=this.view;g.SG(a.Y);a.Cq.dispose();a.H.dispose();a.A&&g.me(a.A);a.B&&a.B.sa()&&g.me(a.B.sa())}x3(this)};
g.h.gF=function(){u3(this.view)};
g.h.oD=function(){u3(this.view)};g.r(kBa,r2);g.r(y3,r2);g.r(lBa,y3);g.r(mBa,r2);g.r(nBa,r2);g.r(pBa,y3);g.r(qBa,y3);g.r(rBa,r2);g.r(z3,r2);I3.prototype.B=function(a,b){var c=g.Ae(b.target,"label");c&&g.T(c,"iv-card-poll-choice-focused",a)};
I3.prototype.G=function(a,b){var c=g.Be(b.target,"iv-card-poll");if(c)if(a.C)g.Vd("iv-card-sign-in-button",c).click();else{var d=parseInt(Eza(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;wBa(a,c);g.HF(this.o.videoData.te,{hd:{action_poll_vote:1},Sb:{poll_id:a.id,index:d,session_token:a.J}});E3(this.o.logger,a.B,void 0,{"link-id":d},a.A.click,
5);(c=g.dI())&&g.PH(c,a.F)}};
I3.prototype.F=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.J,a.G)});
ABa(this,a,!0,c)};
I3.prototype.H=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.La(b,a.R,a.J,a.G));ABa(this,a,!1,b)};g.r(R3,g.J);g.h=R3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.qR(a,b,{id:c});g.K(this,a);a.namespace="annotations_module";d&&zza(a).subscribe("onEnter",d,this);e&&zza(a).subscribe("onExit",e,this);g.$U(this.context.o,[a])};
g.h.Ar=function(){this.context.B.subscribe("resize",this.Jo,this)};
g.h.sa=function(){return this.Ea};
g.h.fl=function(a,b,c,d,e,f,k){this.context.A.X(a,"click",g.La(this.Zp,b,c,d,e,f||[],k||0),this);this.context.A.X(a,"touchstart",g.La(function(){this.zy=!1}),this);
this.context.A.X(a,"touchmove",g.La(function(){this.zy=!0}),this)};
g.h.Zp=function(a,b,c,d,e,f,k){if(this.zy)return!1;k&&(k.stopPropagation(),k.preventDefault());IBa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.fa=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.me(this.sa())};
g.h.Jo=function(){};g.r(U3,R3);g.h=U3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.B.length)(a=this.A.getRootNode())?(a=g.bi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Jo=function(){var a=this.isAvailable();g.L(this.sa(),a);g.T(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);h2(this.A)};
g.h.destroy=function(){this.A.bl(!1);this.A.getRootNode().removeChild(this.G);g.$E(this.L);g.GG(this.ea);this.da&&this.da.dispose();this.H&&this.H.dispose();R3.prototype.destroy.call(this)};
g.h.dO=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.C.scrollTop+=a};
g.h.bG=function(a){if(!g.mr(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.dI(),c=this.o?this.o.oc.D:this.K;b&&c&&q2(b,[c]);this.o=a;V3(this)}g.ei(this.sa())&&(2==this.context.o.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.o.getAdState():void 0):(b=isNaN(void 0)?this.context.o.getPlayerState():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.oc.teaserDurationMs&&this.A.bl(!0,{teaserText:a.oc.teaserText,durationMs:a.oc.teaserDurationMs}));this.na.isActive()||
((!this.D||!this.N.isActive()&&this.aa)&&SBa(this,a),this.na.start(910+a.oc.teaserDurationMs))}};
g.h.KV=function(a){this.D||(this.o=a,V3(this),SBa(this,a),S3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.lK=function(){if(this.D){G3(this.context.logger,this.Z,4,W3(this).A.close);var a=g.dI();a&&this.R&&g.PH(a,this.R);T3(this)}};
g.h.xK=function(){g.T(this.G,"iv-drawer-scrolled",0<this.C.scrollTop)};
g.h.kN=function(){var a=g.dI(),b=W3(this);b=b?b.D:this.K;a&&b&&p2(a,[b])};
g.h.jN=function(){var a=g.dI(),b=W3(this);b=b?b.D:this.K;a&&b&&q2(a,[b])};
g.h.nN=function(){var a=W3(this);H3(this.context.logger,8,a.B,a.A.dW);var b=g.dI();b&&a&&p2(b,[a.H,a.D])};
g.h.mN=function(){var a=g.dI(),b=W3(this);a&&b&&q2(a,[b.H])};
g.h.lN=function(a){var b=W3(this),c=g.dI();this.o?a?(a=this.context.logger,H3(a,9,b.B,b.A.Tx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.PH(c,b.H)):(a=this.context.logger,H3(a,12,b.B,b.A.Tx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.PH(c,b.D)):(a=this.context.logger,G3(a,this.Z,12,b.A.Tx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.K&&g.PH(c,this.K))};
var JBa={collaborator:kBa,donation:lBa,episode:z3,movie:z3,playlist:mBa,poll:nBa,productListing:pBa,simple:y3,tip:qBa,video:rBa};g.r(X3,R3);X3.prototype.Ar=function(){R3.prototype.Ar.call(this);TBa(this)};
X3.prototype.show=function(){R3.prototype.show.call(this);var a=g.dI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&p2(a,[g.LH(b.itct)])};
X3.prototype.hide=function(){R3.prototype.hide.call(this);var a=g.dI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&q2(a,[g.LH(b.itct)])};g.r(Y3,X3);g.h=Y3.prototype;g.h.UV=function(a,b,c,d){this.B.stop();if(!this.C){var e=g.bi(a);this.o||(g.$h(a,e.width),g.$h(b,e.width));g.Jh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Jh(c,"right","1px");this.C=!0;g.L(a,!0);this.D=new g.U(function(){g.S(this.sa(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.ZL=function(a,b){g.or(this.sa(),"iv-branding-active");this.F=new g.U((0,g.A)(function(){g.L(a,!1);this.o||g.$h(b,0)},this),250);
this.F.start();this.C=!1};
g.h.show=function(){if(!this.isActive){X3.prototype.show.call(this);if(!this.G){g.S(this.sa(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.ee("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.L(this.A,!1);var b=g.ee("DIV","branding-img-container",this.A);this.sa().appendChild(b);var c=g.ee("DIV","iv-branding-context-name");g.ue(c,a.channel_name);var d=g.ee("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.x_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.ya(d);b=g.ee("DIV","iv-branding-context-subscribe-caret");c=g.ee("DIV","branding-context-container-inner",b,c,d);g.L(c,!1);d=g.ee("DIV","branding-context-container-outer",c);g.Jh(d,"right",this.H+"px");this.sa().appendChild(d);var e=this.annotation.ab();e&&this.fl(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.B=new g.U(g.La(this.ZL,c,d),500,this);g.K(this,this.B);this.context.A.X(this.sa(),"mouseover",(0,g.A)(this.UV,this,c,d,b,a.image_height));this.context.A.X(this.sa(),"mouseout",(0,g.A)(this.B.start,this.B,void 0));this.G=!0}D3(this.context.logger,this.annotation.o);g.L(this.sa(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.ci(a).width;c=g.Ba(void 0)?void 0:b;g.Qh(a,c);f=new o2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Kza);g.K(this,f);this.context.C.X(f,
"begin",g.La(g.L,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(X3.prototype.hide.call(this),g.L(this.sa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);X3.prototype.destroy.call(this)};g.r(Z3,X3);g.h=Z3.prototype;g.h.show=function(){this.isActive||(X3.prototype.show.call(this),this.K||(UBa(this),this.K=!0),g.L(this.sa(),!0),this.annotation&&this.annotation.o&&D3(this.context.logger,this.annotation.o),g.Pg(function(){g.or(this.sa(),"iv-promo-inactive")},100,this),this.sa().removeAttribute("aria-hidden"),this.isActive=!0,$3(this),WBa(this),XBa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.S(this.sa(),"iv-promo-inactive"),this.isActive=!1,this.sa().setAttribute("aria-hidden",!0))};
g.h.Zp=function(a,b,c,d,e,f,k){return this.D?!1:X3.prototype.Zp.call(this,a,b,c,d,e,f,k)};
g.h.Ku=function(a,b){b.stopPropagation();WBa(this);XBa(this,a);this.o.focus()};
g.h.wL=function(a){this.J=!0;this.Ku(500,a)};
g.h.vL=function(){this.J=!1;VBa(this)};
g.h.CO=function(a){a.stopPropagation();this.hide();F3(this.context.logger,this.annotation.o)};
g.h.lL=function(a){a.stopPropagation();$3(this);this.D=!0;g.S(this.sa(),"iv-promo-collapsed-no-delay");this.F.start();F3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();X3.prototype.destroy.call(this)};g.r(a4,g.nV);g.h=a4.prototype;g.h.Kc=function(a,b){if(!ZBa(g.Y(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Ys(b);c&&c4(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(LBa(this.o,b),h2(this.player)),!0}return null};
g.h.getOptions=function(){return ZBa(g.Y(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Uw=function(){if(this.C){var a=g.RU(this.player).getVideoContentRect(!0);g.ai(this.C.element,a.width,a.height);g.Qh(this.C.element,a.left,a.top)}if(this.o){var b=g.YU(this.player);a=this.o;b=b.width;g.T(a.G,"iv-drawer-small",426>=b);g.T(a.G,"iv-drawer-big",1280<=b)}};
g.h.YS=function(a){this.Rc(a.state);g.X(a.state,2)&&(this.fe()&&this.ue()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.bl(!1))};
g.h.load=function(){g.nV.prototype.load.call(this);this.Rc(g.QU(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.A)(this.CR,this,b,this.J),d=(0,g.A)(function(){this.F=null},this);
g.vH()&&(c=fCa(this,c));c={format:"XML",Ld:c,onError:d,hd:{}};a.isPharma&&(c.hd.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Y(this.player);"gaming"==d.playerStyle&&(c.hd.gaming="1");(b=d.J.get(b))&&gCa(c,b);b=b&&(b.wi||b.Lt);if(!a.Co||b)a.te?$Ba(this,a.te,c):(this.B=(0,g.A)(this.KN,this,c),this.player.addEventListener("videodatachange",this.B));g.eV(this.player,this.C.element,4);this.Uw()};
g.h.Rc=function(a){a=!a.isCued()&&!g.X(a,1024);g.pQ(this.D,a);g.pQ(this.C,a)};
g.h.KN=function(a){var b=this.player.getVideoData();b.te&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),$Ba(this,b.te,a))};
g.h.unload=function(){tBa(this.ob);g.cV(this.player,"annotations_module");g.Jb(this.A,function(a){a.destroy()});
g.Jb(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,h2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.nV.prototype.unload.call(this);g.oQ(this.C);this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.h.CR=function(a,b,c){this.F=null;if(!bCa(this,b,a)&&(a=g.oF(c)&&c.responseXML?c.responseXML:null)){c4(this,a);g.S(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].B,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.C,f.visible=!0);b=new g.qR(c,e,f);a.push(b)}}g.$U(this.player,a)}};
g.h.fF=function(a){a==this.player.getVideoData().videoId&&(this.loaded?hCa(this):this.load())};
g.h.HN=function(a){a=a.getId();var b=this.A[a];b&&!b.B&&(b=b.annotation,kCa(this,a),D3(this.ob,b.o))};
g.h.IN=function(a){d4(this,a.getId())};
g.h.ZB=function(a){a&&(a.hide(),e4(this,"shown",!1,a.annotation.id),this.bp(a.annotation,"hidden"))};
g.h.qG=function(a){a&&(a.show(),e4(this,"shown",!0,a.annotation.id),this.bp(a.annotation,"shown"))};
g.h.rU=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;PAa(d.annotation,function(a){e=e||a.value});
lCa(this,a,b,e)}};
g.h.tQ=function(a){if(a&&a.id){var b=a.ab();if(b){var c=Z2(b);if(c){var d=(0,g.A)(this.bp,this,a,"click");if("new"==Q3(c,b.target)||mCa(this,b))d(),d=null;E3(this.ob,a.o,d)}}}};
g.h.bp=function(a,b){NAa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!mCa(this,c.url))){e=FBa(c.url);var f=EBa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=b4(this).o,g.L0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&b4(this).o.Oc()&&b4(this).o.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.Y(this.player),(d=Z2(c.url))?(f=DBa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.La(GBa,e.pageId,e.Xc),d=new g.vn(d),g.zn(d,e(d.B)),d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=Q3(d,c.url.target),e=a.itct,"ei"in g.tF(d)&&(d=g.ph(d,"ei")),g.AV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.LR=function(){e4(this,"playerControlShow",!1)};
g.h.TT=function(){e4(this,"playerControlShow",!0)};
g.h.JN=function(a){e4(this,"rollOver",!0,a.id)};
g.h.Zh=function(a){e4(this,"rollOver",!1,a.id)};
g.h.ZQ=function(a){a&&a.id&&(this.A[a.id].B=!0,d4(this,a.id),F3(this.ob,a.o),this.bp(a,"close"),e4(this,"closed",!0,a.id))};
g.h.fe=function(){return!!this.o&&this.o.isAvailable()};
g.h.ue=function(){this.fe();return!!this.o&&this.o.D};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.fe();this.o&&(a?c?S3(this.o,c,b):S3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):T3(this.o))};
g.h.bl=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.W=function(){g.Y(this.player).J.unsubscribe("vast_info_card_add",this.fF,this);g.or(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.R,b=0,c=a.length;b<c;b++)g.wH(a[b]);this.R.length=0;g.nV.prototype.W.call(this)};g.VZ.annotations_module=a4;g.VZ.creatorendscreen=I2;})(_yt_player);
